plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tvscreensavermanager'
    compileSdk 34

    defaultConfig {
        applicationId "com.tvscreensavermanager"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
}
